### ISSUE TITLE
Unresolved conflicts commited

### ISSUE THREAD

**Issue by duduBaiao** [dleurs/Flutter-Navigator-2.0-demo-with-Authentication-mecanism#1]
Did you notice this file was committed without solving some conflicts?

https://github.com/dleurs/Flutter-Navigator-2.0-demo-with-Authentication-mecanism/blob/master/lib/src/navigation/my_router_delegate.dart

<img width="652" alt="Screenshot 2021-01-23 at 19 18 50" src="https://user-images.githubusercontent.com/36678/105610469-fec64a00-5daf-11eb-8562-d3ea95283d6c.png">

**Comment by dleurs** [comment]
Thank you !
